variable project_name {}
variable alb_sg_id {}
variable internal_alb_sg_id {}
variable pub_sub_1a_id {}
variable pub_sub_2b_id {}
variable pri_sub_5a_id {}
variable pri_sub_6b_id {}
variable vpc_id {}
variable certificate_domain_name {}
